---
- hosts: masters
  gather_facts: True
  become: yes
  become_method: sudo
  tags:
    - masters
  tasks:
    - name: Get iptables rules
      command: iptables -L --wait
      register: iptablesrules
      check_mode: no

    - name: Open apiserver port with iptables
      command: /sbin/iptables -I INPUT 1 -p tcp --dport 10255 -j ACCEPT -m comment --comment "kube-apiserver"
      when: "'kube-apiserver' not in iptablesrules.stdout"
      notify:
        - restart iptables

    - name: Save iptables rules
      command: service iptables save
      when: "'kube-apiserver' not in iptablesrules.stdout"



- hosts: nodes
  gather_facts: True
  become: yes
  become_method: sudo
  tags:
    - nodes
  tasks:
    - name: Get iptables rules
      command: iptables -L --wait
      register: iptablesrules
      check_mode: no

    - name: Enable iptables at boot
      service: name=iptables enabled=yes state=started

    - name: Open kubelet port with iptables
      command: /sbin/iptables -I INPUT 1 -p tcp --dport 10250 -j ACCEPT -m comment --comment "kubelet"
      when: "'kubelet' not in iptablesrules.stdout"

    # this is needed if the kube-proxy is running in userspace mode
    - name: Allow redirected service traffic
      command: /sbin/iptables -I INPUT 1 -i docker0 -j ACCEPT -m comment --comment "kube-proxy redirects"

    # this is needed if the kube-proxy is running in iptables mode
    - name: Allow DNAT'ed traffic through to docker
      command: /sbin/iptables -I FORWARD 1 -o docker0 -j ACCEPT -m comment --comment "docker subnet"

    - name: Save iptables rules
      command: service iptables save
      when: "'kubelet' not in iptablesrules.stdout"


# https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/iptables.yml
# https://github.com/kubernetes/contrib/blob/master/ansible/roles/master/tasks/iptables.yml
# iptables -A INPUT -p tcp --dport 22 -j ACCEPT
# iptables -A INPUT -p tcp --dport 2376 -j ACCEPT
# iptables -A INPUT -p tcp --dport 2377 -j ACCEPT
# iptables -A INPUT -p tcp --dport 7946 -j ACCEPT
# iptables -A INPUT -p udp --dport 7946 -j ACCEPT
# iptables -A INPUT -p udp --dport 4789 -j ACCEPT



#   # Currently it will disable the REJECT rules and change policy to allow all.
#   # For making pin-pointed rules, one may look at:
#   # https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/iptables.yml
#   # For weave netw plugin, open also: TCP 6783 and UDP 6783/6784



# iptables -A INPUT -p tcp --dport 6783 -j ACCEPT
# iptables -A INPUT -p udp --dport 6783 -j ACCEPT
# iptables -A INPUT -p udp --dport 6784 -j ACCEPT
