apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nginx-welcome.name" . }}

---
# INFO: How do we know which version to use??
# ANSWER: https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "nginx-welcome.fullname" . }}
  # namespace: {{ include "nginx-welcome.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-welcome.name" . }}
    helm.sh/chart: {{ include "nginx-welcome.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # app.kubernetes.io/part-of: "ingress-nginx"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-welcome.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "nginx-welcome.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx-welcome.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "nginx-welcome.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
