apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-welcome.fullname" . }}
  # namespace: {{ include "nginx-welcome.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-welcome.name" . }}
    helm.sh/chart: {{ include "nginx-welcome.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "nginx-welcome.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      # containerPort: 8080
      # nodePort: 30123
  selector:
    app.kubernetes.io/name: {{ include "nginx-welcome.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "nginx-welcome.fullname" . }}
