apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Grafana"
    # The name of the application
    app.kubernetes.io/name: grafana
    # The name of a higher level application this one is part of
    app.kubernetes.io/part-of: ingress-nginx
spec:
  # On production clusters, consider setting up auth for grafana, and
  # exposing Grafana either using a LoadBalancer or a public IP.
  # type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: ui
      # SOURCE: https://kubernetes.io/docs/concepts/services-networking/service/
  selector:
    k8s-app: influxGrafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: ingress-nginx
    addonmanager.kubernetes.io/mode: Reconcile
  type: NodePort
  # type: NodePort
