apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    # What happened to the cluster-service annotation? - https://github.com/kubernetes/dashboard/issues/1849
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "InfluxDB"
    # Why do the yamls in this repo not feature the cluster-service tag that causes it to appear in kubectl cluster-info ?
    # NOTE:
    # dashboard is deployed after cluster creation -> annotation should not be set:
    # kubernetes.io/cluster-service: "true"
    app.kubernetes.io/name: influxdb
    # The name of a higher level application this one is part of
    app.kubernetes.io/part-of: ingress-nginx
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: api
      port: 8086
      targetPort: 8086
  selector:
    # addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: influxGrafana
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: ingress-nginx
  type: NodePort
